/*
Nature API

Read/Write Nature Remo

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ApplianceModel struct for ApplianceModel
type ApplianceModel struct {
	Id *string `json:"id,omitempty"`
	Manufacturer *string `json:"manufacturer,omitempty"`
	RemoteName *string `json:"remote_name,omitempty"`
	Name *string `json:"name,omitempty"`
	// Basename of the image file included in the app. Ex: \"ico_ac_1\" 
	Image *string `json:"image,omitempty"`
}

// NewApplianceModel instantiates a new ApplianceModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplianceModel() *ApplianceModel {
	this := ApplianceModel{}
	return &this
}

// NewApplianceModelWithDefaults instantiates a new ApplianceModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplianceModelWithDefaults() *ApplianceModel {
	this := ApplianceModel{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApplianceModel) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplianceModel) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApplianceModel) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApplianceModel) SetId(v string) {
	o.Id = &v
}

// GetManufacturer returns the Manufacturer field value if set, zero value otherwise.
func (o *ApplianceModel) GetManufacturer() string {
	if o == nil || o.Manufacturer == nil {
		var ret string
		return ret
	}
	return *o.Manufacturer
}

// GetManufacturerOk returns a tuple with the Manufacturer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplianceModel) GetManufacturerOk() (*string, bool) {
	if o == nil || o.Manufacturer == nil {
		return nil, false
	}
	return o.Manufacturer, true
}

// HasManufacturer returns a boolean if a field has been set.
func (o *ApplianceModel) HasManufacturer() bool {
	if o != nil && o.Manufacturer != nil {
		return true
	}

	return false
}

// SetManufacturer gets a reference to the given string and assigns it to the Manufacturer field.
func (o *ApplianceModel) SetManufacturer(v string) {
	o.Manufacturer = &v
}

// GetRemoteName returns the RemoteName field value if set, zero value otherwise.
func (o *ApplianceModel) GetRemoteName() string {
	if o == nil || o.RemoteName == nil {
		var ret string
		return ret
	}
	return *o.RemoteName
}

// GetRemoteNameOk returns a tuple with the RemoteName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplianceModel) GetRemoteNameOk() (*string, bool) {
	if o == nil || o.RemoteName == nil {
		return nil, false
	}
	return o.RemoteName, true
}

// HasRemoteName returns a boolean if a field has been set.
func (o *ApplianceModel) HasRemoteName() bool {
	if o != nil && o.RemoteName != nil {
		return true
	}

	return false
}

// SetRemoteName gets a reference to the given string and assigns it to the RemoteName field.
func (o *ApplianceModel) SetRemoteName(v string) {
	o.RemoteName = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApplianceModel) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplianceModel) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApplianceModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApplianceModel) SetName(v string) {
	o.Name = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *ApplianceModel) GetImage() string {
	if o == nil || o.Image == nil {
		var ret string
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplianceModel) GetImageOk() (*string, bool) {
	if o == nil || o.Image == nil {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *ApplianceModel) HasImage() bool {
	if o != nil && o.Image != nil {
		return true
	}

	return false
}

// SetImage gets a reference to the given string and assigns it to the Image field.
func (o *ApplianceModel) SetImage(v string) {
	o.Image = &v
}

func (o ApplianceModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Manufacturer != nil {
		toSerialize["manufacturer"] = o.Manufacturer
	}
	if o.RemoteName != nil {
		toSerialize["remote_name"] = o.RemoteName
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Image != nil {
		toSerialize["image"] = o.Image
	}
	return json.Marshal(toSerialize)
}

type NullableApplianceModel struct {
	value *ApplianceModel
	isSet bool
}

func (v NullableApplianceModel) Get() *ApplianceModel {
	return v.value
}

func (v *NullableApplianceModel) Set(val *ApplianceModel) {
	v.value = val
	v.isSet = true
}

func (v NullableApplianceModel) IsSet() bool {
	return v.isSet
}

func (v *NullableApplianceModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplianceModel(val *ApplianceModel) *NullableApplianceModel {
	return &NullableApplianceModel{value: val, isSet: true}
}

func (v NullableApplianceModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplianceModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


